cmake_minimum_required(VERSION 3.16)
project(KernelSanity VERSION 0.1.0 LANGUAGES CXX)
add_library(kernelsanity INTERFACE)
add_library(ks::kernelsanity ALIAS kernelsanity)
target_include_directories(kernelsanity INTERFACE ${CMAKE_CURRENT_SOURCE_DIR}/include)
target_compile_features(kernelsanity INTERFACE cxx_std_17)
add_executable(ks_example examples/compare.cpp)
target_link_libraries(ks_example PRIVATE ks::kernelsanity)
include(CTest)
if(BUILD_TESTING)
  add_executable(ks_tests tests/compare_test.cpp)
  target_link_libraries(ks_tests PRIVATE ks::kernelsanity)
  add_test(NAME kernelsanity COMMAND ks_tests)
endif()
